### ISSUE TITLE
Previously Posted Guides

### ISSUE THREAD

**Issue by kayg04** [hetzneronline/community-content#240]
Hello! I had a few questions about the validity and acceptance criteria. 

1. Is it possible to put a link in the footer (or header) in a contributed tutorial to my own blog containing the same tutorial? Ideally my blog will also cross-link to Hetzner's forum post.

2. Is it mandatory that the guide be first posted (after approval) on Hetzner's forum before posting it on my blog? Or is the alternative possible? If so, what would be the timeframe of such a guide before it's considered "too old"?

Thank you.

**Comment by fdrechsler** [comment]
Hello kayg04, 

1. We dont want Links for the sole purpose of SEO. But any Link is appreciated that is relevant to Content in your Guide. So if you want to link to your Blog maybe you find some other Article that has relevance.

2. Are you talking about the Hetzner Forum (forum.hetzner.com)? Because The Forum is in no way involved in the acceptance process of community content. We would like to see unique Content that has been tailored to community.hetzner.com, we do not want reposts. But of course you can repost (even without backlink) your Tutorial any time any where. 

By commiting your Tutorial you are releasing it at public domain, for more information see https://github.com/hetzneronline/community-content/blob/master/LICENSE 

Thank you :) 
Looking forward to see your contributions

Disclaimer: This is not a legal advice.
