### ISSUE TITLE
Connect Plesk with Hetzner DNS

### ISSUE THREAD

**Issue by olho2ls** [hetzneronline/community-content#382]
## Problem
incorrect hostnames 
## Suggested Fix
replace the new hostnames with the old Robot hostnames:

ns1.first-ns.de
robotns2.second-ns.de
robotns3.second-ns.com

link for approval: https://docs.hetzner.com/robot/dedicated-server/operating-systems/plesk/#entering-ns-records-for-the-hetzner-nameservers

**Comment by rook59** [comment]
Actually all nameservers serve the DNS records. The tutorial works because the IP addresses of the old robot hostnames are used for the AXFR transfer, see step 1 https://community.hetzner.com/tutorials/plesk-hetzner-dns#step-1---make-changes-in-plesk

Can you submit a pull request for your suggestion?
