### ISSUE TITLE
Install and configure AWX without using Kubernetes

### ISSUE THREAD

**Issue by f0rk-b0mb** [hetzneronline/community-content#388]
## Problem
Folders are not present:

---

Step 2.5 - Running AWX

Step 2.5.1 - Rendering docker-compose manifest

To render the docker-compose manifest for AWX:

`make docker-auth awx/projects docker-compose-sources`

Step 2.5.2 - Generating UI files

By default, a source deployment of AWX comes without UI files, so we have to build them. Keep in mind that this does take several minutes, depending on your server.

`docker-compose -f tools/docker-compose/_sources/docker-compose.yml run --rm awx_1 make clean-ui ui-devel`

Step 2.5.3 - Running AWX

Once the UI files have been built, we can start AWX with docker-compose:

`docker-compose -f tools/docker-compose/_sources/docker-compose.yml up -d`

**Comment by Hayajiro** [comment]
Hi @f0rk-b0mb

the log output is missing from your description, so I can only guess what the exact issue would be.

I think that you have an issue with copying the logo files from `awx-logos` into AWX. If that's the case, please retry with the following command instead:
```sh
cp /opt/awx/awx-logos/awx/ui/client/assets/favicon.ico \
   /opt/awx/awx-logos/awx/ui/client/assets/logo-header.svg \
   /opt/awx/awx-logos/awx/ui/client/assets/logo-login.svg \
   awx/ui/public/static/media/
```

This is because AWX changed the folder structure a bit in their latest releases.

Two other issues that I found while going through the guide with the latest version are the following:

* The package `python3-pip` is not installed, which the latest versions seem to soft-depend on. Not a breaking change, but you might want to have it installed
* In step 2.5.1, the `make`-step `docker-auth` no longer exists and is no longer required.

I'll update the guide with those changes as soon as I have time for it, but for now, this should get you up and running.

**Comment by f0rk-b0mb** [comment]
Hi @Hayajiro 

Step 2.5.2. & 2.5.3 is also not possible. That YAML files are not existing. I checked every Version from 19.4.0 down to 18.0.0, but I couldn't´t find them in any version.

This folders files: tools/docker-compose/_sources/*
don't exist.

greetz
