### ISSUE TITLE
How to install SmartOS without the need for a USB flash drive

### ISSUE THREAD

**Issue by apeman76** [hetzneronline/community-content#608]
## Problem
It looks like this guide does not work with the newest version any more (or the older one fwiw).

Whenever I get to the part to execute
> [root@ /]# piadm avail

On new versions I get:
piadm avail cannot open /zones/boot/platform-*
And on older versions it wont return any results or errors.

I have tried using ubuntu, debian, and tried not renaming the folder to platform (because the error mentions the dash)
But I am still not able to get past this section and I've already requested the KVM a few times to try and install..

Is there any known fix for this error?

**Comment by svenja11** [comment]
@optaris Can you take a look at this?
Would you be interested in providing an update to your tutorial?

**Comment by apeman76** [comment]
It looks like you might be able to make a bootable zpool after this step. I purchased a USB stick but not manually making the pools got me the next screen which mentioned a 'bootable zpool' on the server itself.

**Comment by optaris** [comment]
Hello,

I'm not aware of any issues with this approach, I used it for the last time on a Hetzner server on September 17, 2022 without any problem. Most probably I used the exact same image version (20210408T001154Z ) as in the documented procedure, but I can't really confirm as I didn't take note of that. (I actually used it several times with a variety of different versions)

Good to know that the version used for the installation in step 3 is not necessarily the version you will ultimately use for running SmartOS, because you can always choose other versions in step 4.

I'm trying to figure out where it goes wrong for you, could you be more specific when referring to newer and older versions so I can try to simulate your problem?

Did you try using the same version as I used in step 3?

From your first message I understand that step 3 worked out well, and that you are having trouble with step 4 and more precisely with the steps related to the manual creation of the zones zpool and the installation of the images.

The renaming of the platform-... directory in step 3 has nothing to do with the actions in step4, so no need to experiment with that. (the renaming is only related to the grub configuration)

The piadm command works by default on the "zones" zpool. In case you chose another name, you will have to adapt the piadm commands.

Are you sure that the zpool you created is bootable?

What is the output of the command:
`
piadm bootable
`
Might be useful to try:
`
piadm bootable -r
`
This command will refresh the MBR or ESP from the bootable zpool, this might be needed due to changes in a mirror or raidz zpool.

What is the output of the command:
`
piadm install 20210701T204427Z
`
Here I'm using an image that is more recent than the one used in step 3.

You do not actually need the `piadm avail` command, that just to obtain a list of possible image names to install.

Happy to help if you can provide me some more detail ;-)

**Comment by optaris** [comment]
Maybe one additional note that might clarify things:

As of SmartOS release-20221215: 
- piadm(8)'s `avail` subcommand now only prints available PIs newer than
 running one that are not installed already.  (OS-8431)

So, if you used the latest image release in step 3 than I would expect that you won't get any output from the command `piadm avail`.

I never tested it, but this behaviour could imply that my procedure isn't working as expected when using "latest" as image release in step 3. I will try to check this.

**Comment by optaris** [comment]
The document was updated to reflect what was discussed here, related to this issue. I hope the new content can be merged soon.

One of the most important changes in the document that was not yet explicitly mentioned: the command below makes that the manual approach also works for newer SmartOS versions.

`piadm bootable -e -i latest zones`

**Comment by svenja11** [comment]
Thank you @optaris for taking the time to look into this issue and for updating the tutorial!
