### ISSUE TITLE
How to install the Pterodactyl game server management panel

### ISSUE THREAD

**Issue by RealZone22** [hetzneronline/community-content#679]
## Problem
The official Panel Discord server does not support the install script and therefore does not offer support.

## Suggested Fix
Remove Panel Discord server from the tutorial or mention they don't give support

**Comment by svenja11** [comment]
@HudsonKnott You wrote the tutorial, can you take a look at this?

**Comment by HudsonKnott** [comment]
Wow, I completely forgot about this! Thanks @svenja11 for the updates you have made. The reason I put the panel discord was because of any possible issues that could arise after a successful installation with the script, which is why I also linked the script's discord, however I can see that this could direct unwanted traffic about installation towards the discord. Not sure if I should add this clarification or just remove it altogether, could I get your opinions?

**Comment by RealZone22** [comment]
I would suggest that you delete the panel Discord server but leave the script Discord server.

**Comment by svenja11** [comment]
It probably won't help you a lot if we both have different suggestions. 😅
But I don't see anything wrong with keeping the Discord server in the tutorial if you make it clear that this is only for issues that are not related to the installation.
