### ISSUE TITLE
Plex has banned Hetzner and the article in it's current form will not work. 

### ISSUE THREAD

**Issue by miah0x41** [hetzneronline/community-content#710]

**Comment by svenja11** [comment]
Hello @miah0x41 
Thank you for pointing this out. We try to keep the tutorials at [community.hetzner.com](https://community.hetzner.com/tutorials) as general as possible so that everyone can follow them — even if they don't have servers at Hetzner. For those who don't have a Hetzner server, the tutorial should still work just fine. However, I can add a hint in the tutorial that points out that this tutorial does not work on Hetzner servers to avoid any confusion.

**Comment by miah0x41** [comment]
Awesome, that's a great suggestion. I didn't check to see if you had one for Emby or Jellyfin, but I could potentially contribute there.
