### ISSUE TITLE
I would like to rent vps, from Vultr, Ionos, Hetzner and Contabo. In each vps of each company.

### ISSUE THREAD

**Issue by Wotan6891** [hetzneronline/community-content#720]
I would like to rent vps, from Vultr, Ionos, Hetzner and Contabo. In each vps of each company have the same web application, any changes are synchronized.

This way if one VPS fails, the other will not fail, I can also organize them depending on the location. And also in case a vps reaches 80% of its resources, another vps already designated will immediately come to its rescue.

Do you know of any software to do this?

**Comment by svenja11** [comment]
Hello @Wotan6891 

I am not sure if this is something that could work for you, but maybe those tutorials could be interesting:

* [Setting up a VPC with site-to-site VPN in Hetzner Cloud](https://community.hetzner.com/tutorials/vpc-with-wireguard-pfsense)
* [Install a Kubernetes cluster on cloud servers](https://community.hetzner.com/tutorials/install-kubernetes-cluster)

The first tutorial explains how to connect two private networks using pfSense and WireGuard. The second tutorial explains how to setup a Kubernetes cluster.

Please note that I have not tested these tutorials for your use case. But maybe this is something you could do some more research on.

------------

Since this is not related to any of our existing tutorials, I will close this issue. However, if you find a way that works for you, feel free to share your solution here. You can also consider to write a tutorial about your solution and submit it to our community:
* [Hetzner Tutorial Guidelines](https://github.com/hetzneronline/community-content/blob/master/contributing.md)

Maybe this can help others too.
