### ISSUE TITLE
Q: do you accept articles with canonical URLs?

### ISSUE THREAD

**Issue by meysam81** [hetzneronline/community-content#822]
Hello Hetzner staff,

I meant to ask a question in the discussion section, yet this repo doesn't have it activated! :(

I'm a blogger and usually post stuff at [my own](https://developer-friendly.blog).
I mean to ask if it is possible to port some of those pieces to your blog, since I mainly write with the infrastructure of Hetzner and it might be valuable to your community to benefit from my tips, tricks and learnings.

Regards.

**Comment by svenja11** [comment]
Hello @meysam81!
Thank you for double-checking, you are probably referring to this [contribution guideline](https://github.com/hetzneronline/community-content/blob/master/contributing.md#content):

> You cannot re-submit any work that is published somewhere else on the web, even if you are the original author.

Unfortunately, we cannot make an exception even though you are using Hetzner servers. But we are always happy about contributions with new content and we do reward them with Hetzner credits. So if you feel like one of your future tutorials could be a great fit for [community.hetzner.com](https://community.hetzner.com/tutorials) rather than your own blog, you are very welcome to create a pull request for that.
