### ISSUE TITLE
Setup your own scalable Kubernetes cluster with the Terraform provider for Hetzner Cloud

### ISSUE THREAD

**Issue by devmaxde** [hetzneronline/community-content#836]
## Problem
Should the Master node be protected by Terraform?

I think Terraform is a huge benefit for managing your own infrastructure. However, if the user is new to Terraform, they might destroy their configuration. Sometimes Terraform rebuilds a Node to apply the new Configuration. That way the Token as well as all user Data is deleted. In Terraform, there is a parameter that prevents a resource from being destroyed. You can simply add the following lines to the configuration:
`  lifecycle {
    prevent_destroy = true
  }`

## Suggested Fix
There should be at least a warning of destroying the entire cluster if you make changes to the Master Node configuration. Maybe even adding the lifecycle protection.

**Comment by svenja11** [comment]
@Blue25GD You wrote the tutorial. Can you take a look at this?

**Comment by Blue25GD** [comment]
Deleting/updating the master node would be a disaster and would destroy the entire cluster with little to no way of recovering, but a normal person wouldn't go around deleting servers from Hetzner randomly and hoping that the cluster still works. If the user modifies the configuration for the master node after creating the cluster, they would have not followed the tutorial correctly and the destruction of the cluster is not because of the contents of the article. Users who will modify the terraform configuration for the master node need to have at least a bit of knowledge about terraform and how kubernetes works. This is why I will not be modifying the article for this issue.

**Comment by devmaxde** [comment]
Well.
I can't say, that I'm happy about the response but I'll accept it. I know, that you need to understand terraform to use it properly. But experts in Terraform won't need your Tutorial. That's why I still think a warning could save some People. But that's not for me to decide.
(I'll mark this as closed, because the Improvement isn't accepted)
